### PR TITLE
Remove forced whitespace after links

### PR DESCRIPTION
**Pull request by gprst**
A whitespace was forced after every link when the markdown was translated to HTML. For instance, something like this:
```md
This is [some link](https://github.com), with a comma right after.
```
would be rendered like this:
```
This is some link , with a comma right after.
```

### CODE REVIEW

**Comment by jakewies** [comment]
Hmm this is interesting. I wonder if anyone working on this file locally and having a formatter like `prettier` running on their files would run into this issue. What do you think @gprst ?

**Comment by gprst** [comment]
No solution occurs to me. This issue has been discussed multiple times (either on [Hugo forum](https://discourse.gohugo.io/t/white-space-issue-in-markdown/25258/6) or on [Hugo GitHub repo](https://github.com/gohugoio/hugo/issues/6832)), and the answer of [bep](https://github.com/bep) at the time was that [you can use a linter in many situations, but should not in this one](https://github.com/gohugoio/hugo/issues/6832#issuecomment-580868004).

I imagine one can set up their linter to format files *only on save*. And since this file isn't supposed to change much (if at all), it should be fine and stay the same without any unwanted new line addition.

**Comment by gprst** [comment]
Also another workaround would be to configure the theme to use Blackfriday instead of Goldmark (the default) as a markdown formatter, but Blackfriday [will eventually be deprecated](https://gohugo.io/content-management/formats/#list-of-content-formats), which is to keep in mind.

**Comment by jakewies** [comment]
Ok in that case I think this should be a default in the project. Thanks for the fix!

**Pull request merged**
