### PR TITLE
Migrate to SCSS assets

### PR DESCRIPTION
**Pull request by kentnek**
Fix for #14.

This PR does a few things:
- Translate all Stylus to SCSS (using [stylus-converter](https://github.com/txs1992/stylus-converter))
- Move SCSS and JS to `assets/`, where Hugo can discover/transpile/minify them automatically.
- Remove gulp and babel
- Add a `custom.scss` file so users can add in their own styling, which is loaded next to the main styles.

@jakewies I've tested this locally and the translated styles appear to look the same. Could you help me test as well, in case I miss something? 

WIP: move style variables (such as primary colors) to the site's config so it's easier for users to change them, and some documentations.

### CODE REVIEW

**Comment by jakewies** [comment]
@kentnek fyi I believe you can open the PR as a draft and it is treated the same as a WIP

**Comment by jakewies** [comment]
> @jakewies I've tested this locally and the translated styles appear to look the same. Could you help me test as well, in case I miss something?

Yes absolutely I can test them out. When you say they "appear to look the same", I assume you are saying that in a good way? As in, you didn't miss anything?

**Comment by jakewies** [comment]
In regards to the `custom.scss` file, how is this supposed to work in theory? I see it is empty. So the file exists, but no styles are in it. If someone wants to add their own styling, what steps would they need to take?

Sorry for the 3rd comment in a row, I'm spazzing lol

**Comment by kentnek** [comment]
> you can open the PR as a draft
Oooh I didn't know about this.

> I assume you are saying that in a good way
Oh yes sorry for the confusion. What I meant was, since you are the original author and probably know the styles in and out, you should probably look through the exampleSite and see if something is off. 

This is a major change, and although I used a tool to convert the stylus files, there were still places I had to go in and fix manually (string interpolation, partial imports, etc).

> If someone wants to add their own styling, what steps would they need to take?
They just need to make their own copy of `custom.scss` file and write their styles in there. The theme would always compile and include that custom file in every page.

I see other themes are doing this as well.

**Comment by jakewies** [comment]
> since you are the original author and probably know the styles in and out

Don't be so sure of that 🤣 It's been a while since I wrote these styles.

>  I used a tool to convert the stylus files

Neat! Share with the class 😄 

> They just need to make their own copy of custom.scss file and write their styles in there. The theme would always compile and include that custom file in every page.

This is awesome

---

Ok, I'll give everything a once over! Might take me some time but should be able to knock it out before the end of the weekend.

**Comment by jakewies** [comment]
We can remove the `yarn.lock` file and `node_modules` now that we aren't relying on any `npm` packages.

**Comment by jakewies** [comment]
Styles look good! One question: with the introduction of `scss` and `js` in the `assets/` directory, do we need the `static/css` and `static/js` directories anymore?

Other than that question and the comment above about `yarn.lock` and `node_modules`, this PR looks solid to me. Great work @kentnek !

**Comment by kentnek** [comment]
> do we need the static/css and static/js directories anymore?

Right, I actually forgot to remove them.

> we can remove the yarn.lock file and node_modules

Yup, those too.

Other than that, what's left for me is adding some more documentations (users need to use `hugo-extended` for scss support) and tweaking the scss variables a bit.

**Comment by kentnek** [comment]
@jakewies Okay I make a few more changes:
- remove the unnecessary files as discussed
- previously the static css files would be generated to `static/scss/pages/<name>.css`. Now they are exported to `static/css/<name>.css`.
- add some documentations regarding custom styling.

**Comment by jakewies** [comment]
@all-contributors please add @kentnek for doc

**Comment by jakewies** [comment]
@all-contributors please add @kentnek for design

**Pull request merged**
