### PR TITLE
Fix division usage in stylus for headers

### PR DESCRIPTION
**Pull request by kentnek**
For H3, H4 and H5, the stylus definition is not defined correctly, so the browser falls back to user agent stylesheet.
image

Even my IDE is complaining about them:
image

This is because [the division operator needs to be wrapped inside parentheses](https://stackoverflow.com/a/27304995).

So I just put in some parens and correct the division constants so the header sizes look similar to Chrome's user agent stylesheet. We can also choose to remove these `font-size` declaration but I think explicit sizing is better.

### CODE REVIEW

**Comment by jakewies** [comment]
@kentnek what are your thoughts on this branch after our conversation in https://github.com/jakewies/hugo-theme-codex/issues/14

**Comment by kentnek** [comment]
I think I can group this with my scss translation, but it might take some time.

**Comment by jakewies** [comment]
I'll leave this open for now and if things change we can merge 👍

**Comment by kentnek** [comment]
Closed as this will be addressed in #33.

**Pull request closed without merging**
