### PR TITLE
Change how prismjs is loaded.

### PR DESCRIPTION
**Pull request by jlebar**
- Load minified code (3kB vs 30kB)
 - Add prism autoloader so that we get highlighting for languages we
   use.
 - Hardcode exact prism version.  Perhaps this is controversial, but it
   saves a redirect for each request, shaving off 30ms on a fast
   connection.

### CODE REVIEW

**Comment by kentnek** [comment]
> Load minified code (3kB vs 30kB)

Aw yiss.

> Add prism autoloader so that we get highlighting for languages we use.

Oh this is pretty cool, thanks for pointing this out.

> Hardcode exact prism version.

We're already using `1.2` instead of `1.x.x`, so changing to the exact version makes sense here too.

I'm good with this @jakewies :D

**Comment by jakewies** [comment]
Great additions! I didn't realize there was an autoloader 🤯

**Comment by jakewies** [comment]
@kentnek do you have merge perms? I think you should. If you do go ahead and merge this in and you can add @jlebar as a contributor using the @all-contributor command! If you don't have merge perms let me know and I'll figure out what to do to get you them. 😄

**Comment by jakewies** [comment]
Awesome stuff @jlebar thank you for contributing!

**Comment by kentnek** [comment]
@jakewies Oh cool let me do that!

**Comment by kentnek** [comment]
@all-contributors please add @jlebar for code.

**Pull request merged**
