### PR TITLE
Rename /static/icons to /static/images/social

### PR DESCRIPTION
**Pull request by pyvain**
Pull request for the issue #47 

I moved icons from /static/icons to /static/images/social and changed the path is the impacted partial

### CODE REVIEW

**Comment by kentnek** [comment]
Thanks for the PR! A few notes:
- [ ] There's this `/icons/chevron-left.svg`, which is not a social icon. Could you move it to `/images/`?
- [ ] Please help us update the README.md, more specifically the section on how to add new social icons.

**Comment by pyvain** [comment]
Here it is!

**Comment by kentnek** [comment]
This looks great to me. Can we merge this? @jakewies

**Comment by jakewies** [comment]
Yup looks good!

**Comment by jakewies** [comment]
@all-contributors please add @pyvain for code, doc

**Pull request merged**
