### PR TITLE
Add overrides.scss

### PR DESCRIPTION
**Pull request by jakewies**
Fixes https://github.com/jakewies/hugo-theme-codex/issues/51

## Changelog

- Add `assets/scss/overrides.scss` and import after all variables have been declared
- Update README

### CODE REVIEW

**Comment by jakewies** [comment]
@kentnek let me know your thoughts on this implementation. It seems to work out pretty well. All that's needed is to add an `assets/scss/overrides.scss` file and override any of the supported variables. I think we could continue to document which variables are overridable as the needs arise. 

You could technically override any variable defined before the `overrides.scss` file is imported, but I've only documented `$primary` right now.

**Comment by kentnek** [comment]
oh nice work!

one small thing though: currently the `_vars.scss` file imports two other partials:
```
@import "_colors";
@import "_screenSizes";
```
Is it possible for us to merge both into `_vars.scss` so that it's clearer which variables can be overrides? Keeping them separate don't seem to be useful either as other concrete `scss` still need to import all these basic partials.

**Comment by jakewies** [comment]
You know what's funny, I had the same inclination and started working on it in this PR and then realized that other partials are importing `_colors` as well (not vars). These partials include:

```
partials/_post-list.scss
partials/_reset.scss
```

Feels like circular dependency hell in there. I think what we could do is add `_colors` and `_screenSizes` into `_vars` and then import `_vars` into the two partials listed above. That should work out just fine.

I'll knock that out in the AM.

**Comment by jakewies** [comment]
I've been a bit busy with RL, but got around to updating this. I did a few things in the last commit:

- Combined `_colors.scss` and `_screenSizes.scss` into the `_vars.scss` file
- Removed any imports of these two files in other scss files
- Removed any `@import "vars"` from other scss files, as it seems redundant because vars is now being imported as the first partial in `_main`.

Everything is working as expected. Let me know what you think @kentnek

**Comment by kentnek** [comment]
hey sorry I've been swamped with work too. The PR looks good! I'll merge it now.

**Comment by jakewies** [comment]
Good catch. I thought they were regenerated. I'll do that now.

**Comment by kentnek** [comment]
okay then this is good to go!

**Pull request merged**
